development:
  cloud_name: "@dqaturjpm"
  api_key: "172867358721737"
  api_secret: "fzKOZavzETwslxbCmAfTtrlEmPc"
  secure: true

production:
  cloud_name: "@dqaturjpm"
  api_key: "172867358721737"
  api_secret: "fzKOZavzETwslxbCmAfTtrlEmPc"
  secure: true

