default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "g_portfolio_development") %>
  username: <%= ENV.fetch("DB_USER_DEVELOPMENT", ENV["USER"]) %>
  password: <%= ENV["DB_PASSWORD_DEVELOPMENT"] %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "g_portfolio_test") %>
  username: <%= ENV.fetch("DB_USER_TEST", ENV["USER"]) %>
  password: <%= ENV["DB_PASSWORD_TEST"] %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION") %>
  username: <%= ENV.fetch("DB_USER_PRODUCTION") %>
  password: <%= ENV.fetch("G_PORTFOLIO_DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  sslmode: require
