default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # On utilise ENV pour le host et le port si fournis, sinon défaut localhost:5432
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "g_portfolio_development") %>
  username: <%= ENV.fetch("DB_USER_DEVELOPMENT", ENV["USER"]) %>
  password: <%= ENV["DB_PASSWORD_DEVELOPMENT"] %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "g_portfolio_test") %>
  username: <%= ENV.fetch("DB_USER_TEST", ENV["USER"]) %>
  password: <%= ENV["DB_PASSWORD_TEST"] %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION", "g_portfolio_production") %>
  username: <%= ENV.fetch("DB_USER_PRODUCTION", "g_portfolio") %>
  password: <%= ENV["G_PORTFOLIO_DATABASE_PASSWORD"] %>
  # Si tu utilises Render ou un autre service cloud, n'oublie pas d'utiliser les variables DB_HOST et DB_PORT
