default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  # Utiliser DATABASE_URL si disponible (Render fournit cette variable)
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "g_portfolio_development") %>
  username: <%= ENV.fetch("DB_USER_DEVELOPMENT", ENV["USER"]) %>
  password: <%= ENV["DB_PASSWORD_DEVELOPMENT"] %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "g_portfolio_test") %>
  username: <%= ENV.fetch("DB_USER_TEST", ENV["USER"]) %>
  password: <%= ENV["DB_PASSWORD_TEST"] %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION", "portfolio_db_0bgs") %>
  username: <%= ENV.fetch("DB_USER_PRODUCTION", "portfolio_db_0bgs_user") %>
  password: <%= ENV.fetch("G_PORTFOLIO_DATABASE_PASSWORD", "aWEBj1yjnGRllmzJl8SKdatOOQLxksij") %>
  host: <%= ENV.fetch("DB_HOST", "dpg-d3s9qhc9c44c73ckfmog-a.frankfurt-postgres.render.com") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  sslmode: require
